# Test blocks

It looks like a bug found its way into our code! But before you do anything, let's run the tests to help us figure out what's wrong. In the end, that's exactly what we write them for, isn't it?

```sh nonumber
npx tsx greet.ts
```

```
Error: Expected Hello, ${name}! to equal to Hello, John!
```

We can see a failing assertion but it never points us to the problematic code or even the test. We can likely guess the issue is with the `greet()` function based on the expected string but that assumption is only viable because we have just two tests at the moment. But what will happen once we have three, thirty, three hundred tests? Suddenly, we can't assume anymore and have to spend a lot of time trying to _debug the test_ instead of _fixing the issue_.

More to that, since both assertions are in the same scope, if the first one throws, the second will never even run!

Let's address this shortcoming by giving each test its own room to live in. Because just as we have benefited from a declarative `expect()` abstraction, we can save ourselves hours of confusion simply by providing a more declarative `test()` API for our tests:

```ts
test('first test', () => {
	expect(actual).toBe(expected)
})

test('second test', () => {
	expect(actual).toBe(expected)
})
```

> 🦉 Giving each test a good test name vastly improves how you (and others) understand the intention behind the test. Learn [How to Write Better Test Names](https://www.epicweb.dev/talks/how-to-write-better-test-names).

```
✗ first test
  Error: Expected "5" to equal to "10"

✓ second test
```

🐨 Your goal right now is to write the `test()` function and wrap both existing tests in it. As the result, it should print the correct test status (success/failure) for each test.

<callout-info>
	Tip: Since the `expect()` assertions _throw_ when something is wrong with the
	tested code, perhaps you should _try_ and _catch_ those assertion errors!
</callout-info>

🐨 Once you wrap the existing tests in the new `test()` function, see if you can spot which test is failing and fix the issue.
